version: '3'
services:
  #context-broker:
  #  image: 'diwise/context-broker:latest'
  #  build:
  #    context: ..
  #    dockerfile: ./deployments/Dockerfile
  #  restart: always
  #  depends_on:
  #    - orion-ld
  #  volumes:
  #    - ./configs/context-broker.yaml:/opt/diwise/config/default.yaml
  #  ports:
  #    - '8080:8080'

  orion-ld:
    image: 'quay.io/fiware/orion-ld@sha256:d1c2b50ba47046c2dd0bcd786970469e21d6998b08ad09b56da8fb17cd267ef6'
    restart: always
    command: [ '-experimental', '-logLevel', 'DEBUG' ]
    environment:
      ORIONLD_MONGO_HOST: 'mongodb'
      ORIONLD_MONGO_USER: 'admin'
      ORIONLD_MONGO_PASSWORD: 'password'
      ORIONLD_TROE: 'TRUE'
      ORIONLD_TROE_USER: 'postgres'
      ORIONLD_TROE_PWD: 'password'
      ORIONLD_TROE_HOST: 'timescale'
      ORIONLD_LOG_FOR_HUMANS: 'TRUE'
      ORIONLD_DISABLE_FILE_LOG: 'TRUE'
    depends_on:
      mongodb:
        condition: service_healthy
      timescale:
        condition: service_healthy
    ports:
      - '1026:1026'
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:1026/ngsi-ld/v1/types"
        ]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 30s

  timescale:
    image: timescale/timescaledb-ha:pg14-latest
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 10s
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - "5432"

  mintaka:
    image: fiware/mintaka:0.6.6
    restart: always
    depends_on:
      timescale:
        condition: service_healthy
    environment:
      DATASOURCES_DEFAULT_HOST: 'timescale'
      DATASOURCES_DEFAULT_USERNAME: 'postgres'
      DATASOURCES_DEFAULT_PASSWORD: 'password'
      DATASOURCES_DEFAULT_DATABASE: 'orion'
      BASEPATH: '/ngsi-ld/v1'    
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 2s
      timeout: 2s
      retries: 30
      start_period: 5s
    ports:
      - "1027:8080"

  mongodb:
    image: mongo:5
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongo",
          "--port",
          "27017",
          "-u",
          "admin",
          "-p",
          "password",
          "--eval",
          "\"db.adminCommand('ping')\""
        ]
      interval: 5s
      timeout: 1s
      retries: 12
      start_period: 10s
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'password'
    ports:
      - '27017'
    command: --nojournal --quiet
    volumes:
      - mongo-db:/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@diwise.io
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin      

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: 'mongodb'
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_AUTH_DATABASE: 'admin'
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'admin'
      ME_CONFIG_MONGODB_ADMINPASSWORD: 'password'
      ME_CONFIG_BASICAUTH_USERNAME: ''
    depends_on:
      orion-ld:
        condition: service_healthy
    ports:
      - '5051:8081'

volumes:
  mongo-db: ~
  pgadmin-data: ~
